const galleryAssets = [
  "assets/1 Videos/rony_vivas_fotografo.mp4",
  "assets/1 Videos/rori_1min_3.mp4",
  "assets/2 Comercial/Avilas/avila_petare_1.jpeg",
  "assets/2 Comercial/Avilas/captura_de_pantalla_2020-05-09_a_las_4.46.53_p.m..png",
  "assets/2 Comercial/Avilas/captura_de_pantalla_2020-05-09_a_las_4.47.17_p.m..png",
  "assets/2 Comercial/Avilas/caracas_desde_bello_monte.jpeg",
  "assets/2 Comercial/Corporativo/1 QM8A0819.jpg",
  "assets/2 Comercial/Corporativo/10 QM8A0300.jpg",
  "assets/2 Comercial/Corporativo/11 QM8A0563.jpg",
  "assets/2 Comercial/Corporativo/12 QM8A1314.jpg",
  "assets/2 Comercial/Corporativo/2 QM8A0333.jpg",
  "assets/2 Comercial/Corporativo/3 QM8A0574.jpg",
  "assets/2 Comercial/Corporativo/4 QM8A0759.jpg",
  "assets/2 Comercial/Corporativo/5 QM8A0397.jpg",
  "assets/2 Comercial/Corporativo/6 156A7697.jpg",
  "assets/2 Comercial/Corporativo/7 6A8191.jpg",
  "assets/2 Comercial/Corporativo/8 QM8A0022.jpg",
  "assets/2 Comercial/Corporativo/9 QM8A0097.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0014.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0031.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0034.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0101.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0109.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0185.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0199.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0220.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A0266.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A9827.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A9852.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A9949.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A9975.jpg",
  "assets/2 Comercial/Deportivas/Cori Urosa, Yoga/QM8A9986.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3247.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3290.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3308.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3322.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3404.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3424.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3437.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3470.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3512.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3546.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3609.jpg",
  "assets/2 Comercial/Deportivas/Funcionales, Sunseat/QM8A3666.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9100.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9287.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9330.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9486.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9566.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9584.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9606.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9640.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9661.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9684.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9704.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9742.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9795.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9832.jpg",
  "assets/2 Comercial/Deportivas/Regata, Puerto Azul/QM8A9900.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/1 _m8a0263.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/2 _m8a0315.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/3 _m8a0359.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/4 _m8a9911.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/5 _m8a9981.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/6 _mg_8545.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/7.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/8.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/9.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/agrado23_alasagrado23.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/aquejuaco_pepitocarne.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/arkbar_milanesadepollo.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/arkbar_pastarigatonicapressa.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/bravopizzacaracas_cuadradaanchoasyaceitunas3.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/bravopizzacaracas_redondamargarita1.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/corazoncontento_empanadaasadonegro.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/desayunarteccs_empanadahorneadaquesosyespinaca.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/elreydelpernil_shawarmapernil.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/horneadoshygge_cruffings.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/horneadoshygge_panmasamadrearandanosnueces.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/lacreme_danesademanzana-20.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/lacreme_danesademanzana-27.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/lapanaderia_cachitotapara.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/latascadejuancho_chicharrondecostilla.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/nanhai_cerdoasado.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/odc_reposteria_galletademantequillapequena13.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/onheltlyfood_causavegana.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/onheltlyfood_hamburguemonster-impossible2.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/paradormediterraneo_cremalangostinos.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/pausastreetfood_hiphop.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/rosso_appelpie3.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/rosso_burrata5.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/sweetfactory_hamburguesalasifrina.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/trohermanosfood_ensaladadecangrejo.jpg",
  "assets/2 Comercial/Fotos de Menu Pedidos Ya/trohermanosfood_inaroll.jpg",
  "assets/3 Retratos/Ângel_caído/img_8366-edit.jpg",
  "assets/3 Retratos/Ângel_caído/img_8398.jpg",
  "assets/3 Retratos/Ângel_caído/yubi_acostada.jpg",
  "assets/3 Retratos/Indestructible/indestructible_1.jpg",
  "assets/3 Retratos/Indestructible/indestructible_2.jpg",
  "assets/3 Retratos/Indestructible/indestructible_3.jpg",
  "assets/3 Retratos/Indestructible/indestructible_4.jpg",
  "assets/3 Retratos/Indestructible/indestructible_5.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/andreína_maris_yoguini.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/bartender_ccct.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/césar_lindarte_cinta_negra_de_karate.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/choco_giraldo_campeón_suramericano_de_freestile.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/daniel_suarez_artista_plástico_contemporáneo.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/daniela_román_paseadora_de_perros.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/donaldo_barros_fotógrafo_.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/eilein_ugueto_bailarina_tradicional.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/fernando_silva_tapicero_y_sillogo.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/gladys_rodríguez_periodista.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/img_2363.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/img_4208-edit.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/img_8507.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/img_9576.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/img_9888.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/jesús_barrios.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/josé_castillo_premio_municipal_de_artes:cine_2012:14.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/josé_miguel_villegas.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/juvenal_ravelo.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/luis_julio_toro_músico.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/mercedes_gómez_atleta_paralimpica.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/oliboy.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/qm8a2799.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/ronyvivasselecc-3.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/santiago_pol_diseñador_gráfico.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/sergio_monsalve_periodista_y_crítico_de_cine.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/sofia_simón_maestra_del_color_.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/trofeo_viviente.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/unai_amenabar_periodista.jpg",
  "assets/3 Retratos/La_luz_que_llevamos_dentro/yoel_reyna_tejedor_de_redes.jpg",
  "assets/3 Retratos/Retratos_de_estudio/1 captura_de_pantalla_2020-11-10_a_la(s)_16.30.13.png",
  "assets/3 Retratos/Retratos_de_estudio/10img_9281.jpg",
  "assets/3 Retratos/Retratos_de_estudio/11img_9382-edit.jpg",
  "assets/3 Retratos/Retratos_de_estudio/12yubi_lamcome_2.jpg",
  "assets/3 Retratos/Retratos_de_estudio/13.jpg",
  "assets/3 Retratos/Retratos_de_estudio/2 img_2513.jpg",
  "assets/3 Retratos/Retratos_de_estudio/3 img_1880.jpg",
  "assets/3 Retratos/Retratos_de_estudio/4 captura_de_pantalla_2020-11-10_a_la(s)_16.32.32.png",
  "assets/3 Retratos/Retratos_de_estudio/5 cp8a2550.jpg",
  "assets/3 Retratos/Retratos_de_estudio/6 captura_de_pantalla_2020-11-10_a_la(s)_16.32.44.png",
  "assets/3 Retratos/Retratos_de_estudio/7 captura_de_pantalla_2020-11-10_a_la(s)_16.33.32.png",
  "assets/3 Retratos/Retratos_de_estudio/8 captura_de_pantalla_2020-11-10_a_la(s)_16.33.06.png",
  "assets/3 Retratos/Retratos_de_estudio/9img_5307.jpg",
  "assets/4 Documental/Caruao/caruao.jpg",
  "assets/4 Documental/Caruao/caruao_2.jpg",
  "assets/4 Documental/Caruao/img_6098.jpg",
  "assets/4 Documental/Caruao/img_6105.jpg",
  "assets/4 Documental/El_Tigre/img_3105.jpg",
  "assets/4 Documental/El_Tigre/img_3405.jpg",
  "assets/4 Documental/El_Tigre/img_3520.jpg",
  "assets/4 Documental/El_Tigre/img_3597.jpg",
  "assets/4 Documental/El_Tigre/img_3746.jpg",
  "assets/4 Documental/El_Tigre/niñas_de_akatompo_ronyvivas_(tascabaña_anzoátegui__2012).jpg",
  "assets/4 Documental/El_Tigre/tendedero_ronyvivas_(tascabaña_anzoátegui__2012).jpg",
  "assets/4 Documental/El_Tigre/visitantes_de_akatompo_ronyvivas_(tascabaña_anzoátegui__2012).jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_1.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_10.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_11.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_12.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_13.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_14.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_15.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_16.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_2.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_3.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_4.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_5.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_6.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_7.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_8.jpg",
  "assets/4 Documental/Gallera_Caracas/rony_vivas_9.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a2834.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a2854.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3121.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3129.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3132.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3174.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3227.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3241.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3242.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3246.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3265.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3271.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3302.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3317.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3327.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3333.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3378.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3380.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3401.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3412.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3418.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3448.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3454.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3486.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3495.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3511.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3581.jpg",
  "assets/4 Documental/Madrid/madrid_noche1_/qm8a3591.jpg",
  "assets/4 Documental/Padre_e_Hijo/dsc_5748.jpg",
  "assets/4 Documental/Padre_e_Hijo/dsc_5755.jpg",
  "assets/4 Documental/Padre_e_Hijo/img_7619.jpg",
  "assets/4 Documental/Padre_e_Hijo/img_7636.jpg",
  "assets/4 Documental/Padre_e_Hijo/img_7665.jpg",
  "assets/4 Documental/Padre_e_Hijo/img_7706.jpg",
  "assets/4 Documental/Padre_e_Hijo/img_7789.jpg",
  "assets/4 Documental/Yugo_Heredado/img_7599.jpg",
  "assets/4 Documental/Yugo_Heredado/img_7604.jpg",
  "assets/4 Documental/Yugo_Heredado/img_7733.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8349.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8388.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8400.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8410.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8456.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8611.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8668.jpg",
  "assets/4 Documental/Yugo_Heredado/img_8717.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Caricuao/15.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Caricuao/autoretrato.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Caricuao/bloque_14.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Caricuao/caricuao.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/apagon.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/avila.jpeg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/bandera_completa.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/batalla2_.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/dia_de_la_juventud.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/el_calvario.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/estudiantes.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/falta_de_agua.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/just.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/libertador.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/los_proceres.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/monja.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/protestas_en_venezuela.png",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/salud.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/santa_fe.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Diégesis/voluntrarios.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/23_2.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/3059.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/bicivallearriba_lista.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/caracas_en_bici.png",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/img244-2.jpg",
  "assets/7 Trabajos personales/Estenopeicas/Unicas/margarita.jpg",
  "assets/7 Trabajos personales/Estenopeicas/arqueologia.pdf",
  "assets/7 Trabajos personales/Fotografía digital/Lecerca/6.png",
  "assets/7 Trabajos personales/Fotografía digital/Lecerca/ale_1.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Lecerca/ale_retrato_1.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Lecerca/ale_retrato_3.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Lecerca/captura_de_pantalla_2019-01-28_a_la(s)_10.55.40_a.m..png",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6731.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6747.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6748.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6749.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6765.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6767.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6785.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6798.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Legado/img_6806_copy.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Muñecas/_m8a6883.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Muñecas/_m8a9514.jpg",
  "assets/7 Trabajos personales/Fotografía digital/Muñecas/_m8a9543.jpg",
  "assets/Logo Rony Blanco.png",
  "assets/Logo Rony negro.png",
  "assets/favicon logo-black.png",
  "assets/favicon.png",
  "assets/instagram_story_mockup.png",
  "assets/logo-white.png",
  "assets/pedidosya-logo-png_seeklogo-363652.png",
  "assets/static/video_landing.mp4"
];